version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    build:
      context: .
    command: yarn start:dev
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_SYNCHRONIZE=true
    volumes:
      - .:/car-dealership
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
